# Generated by Django 4.1.6 on 2023-03-11 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='blog/')),
                ('post_by', models.CharField(default='Admin', max_length=200)),
                ('post_on', models.DateField(default=datetime.date(2023, 3, 11))),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
    ]
