# Generated by Django 4.1.6 on 2023-04-01 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_decoration_price_alter_blogs_post_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='menu',
            name='photo',
            field=models.ImageField(default='', upload_to='menu/'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 1)),
        ),
    ]
