# Generated by Django 4.1.6 on 2023-04-05 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_remove_menu_description_alter_blogs_post_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='items',
            new_name='descriptions',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 5)),
        ),
    ]
