# Generated by Django 4.1.6 on 2023-04-05 05:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0009_rename_items_menu_descriptions_alter_blogs_post_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
