# Generated by Django 4.1.6 on 2023-04-05 11:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0010_remove_menu_descriptions_menu_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
            field=tinymce.models.HTMLField(default='', max_length=100),
        ),
    ]
