# Generated by Django 4.1.6 on 2023-04-05 11:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0011_remove_menu_description_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
