# Generated by Django 4.1.6 on 2023-04-07 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0013_packages_alter_blogs_post_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='photo',
            field=models.ImageField(default='', upload_to='packages/'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 7)),
        ),
    ]
