# Generated by Django 4.1.6 on 2023-04-11 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0014_packages_photo_alter_blogs_post_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='eventid',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 11)),
        ),
    ]
