# Generated by Django 4.1.6 on 2023-04-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0015_remove_packages_eventid_alter_blogs_post_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='choices',
            field=models.CharField(default='', max_length=100),
        ),
    ]
