# Generated by Django 4.1.6 on 2023-04-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0016_packages_choices'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packages',
            table='packages',
        ),
    ]
