# Generated by Django 4.1.6 on 2023-04-12 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0017_alter_packages_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 12)),
        ),
    ]
