# Generated by Django 4.1.6 on 2023-04-18 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0018_alter_blogs_post_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('EventDate', models.CharField(max_length=100)),
                ('ContactNumber', models.CharField(max_length=100)),
                ('NoofGuests', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('EventTime', models.CharField(max_length=200)),
                ('venueEventAddress', models.TextField()),
                ('selectevent', models.CharField(max_length=100)),
                ('selectdecoration', models.CharField(max_length=100)),
                ('selectpackages', models.CharField(max_length=100)),
                ('TellusYourNeeds', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 18)),
        ),
    ]
