# Generated by Django 4.1.6 on 2023-04-20 05:08

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0019_booking_alter_blogs_post_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='', upload_to='Vendorcategory/')),
            ],
            options={
                'db_table': 'Vendorcategory',
            },
        ),
        migrations.CreateModel(
            name='Vendordetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='', upload_to='packages/')),
                ('location', models.CharField(default='', max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('vcategory', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Vendordetail',
            },
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 20)),
        ),
    ]
