# Generated by Django 4.1.6 on 2023-04-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0022_alter_vendor_photo_alter_vendor_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordetail',
            name='vcategory',
        ),
    ]
