# Generated by Django 4.1.6 on 2023-04-25 04:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0023_remove_vendordetail_vcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetail',
            name='vendorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventapp.vendor'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 25)),
        ),
    ]
