# Generated by Django 4.1.6 on 2023-05-04 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0024_vendordetail_vendorid_alter_blogs_post_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 5, 4)),
        ),
    ]
